[project]
name = "ComfyUI-prompt-formula"
description = "ComfyUI-prompt-formula"
version = "1.6.1"
license = {file = "LICENSE"} 
dependencies  = [torch>=2.0.0]

[project.urls]
Repository = "https://github.com/a63976659/ComfyUI-prompt-formula"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "a63976659"
DisplayName = "ComfyUI-prompt-formula"
Icon = ""
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

